feat: auto extend customer customerItems if already in possesion upon order
boklisten/bl-web pull request #394
Opened 2023-06-12 19:36 UTC by AdrianAndersen

Make it so that the if an item in a customer order is already in their possession: extend that item according to the extendPeriod set on the branch.

There are A LOT of ugly code here, because the cart system is really whack. But I tested it with Ullern VG2 ST, by setting an extend period for that branch. (next year, price 0) Then I gave myself a customerItem. Lastly, order the same item as the customerItem, and see the magic happen. 😉

2023-06-12 20:34 UTC, LarsSelbekk commented on src/app/cart/cart.service.ts
> +				periodType: "semester",
Will it always be a semester? Won't the public school students only order new books once a year, thus losing their books after a semester?

2023-06-12 21:14 UTC, LarsSelbekk requested changes
Looking as good as it can, but I would like to know more about periodType before approving

2023-06-12 21:18 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Forlenging av bøker ved bestilling](https://trello.com/c/duxliqpH/659-h%C3%A5ndtere-folk-som-skal-beholde-b%C3%B8ker-over-flere-semestre-i-matching)

2023-06-13 13:31 UTC, AdrianAndersen commented on src/app/cart/cart.service.ts
> +				periodType: "semester",
PeriodType is actually kinda redundant. It is alway "semester", and there is no real logic to support for instance "year". I guess it was initially implemented to enable difference in extensions depending on whether it was for an entire year or only a semester. In practise, we have to use "semester", otherwise weird things start to happen 🤷‍♂️

2023-06-13 15:02 UTC, merged