bl next linking
boklisten/bl-web pull request #400
Opened 2023-07-02 10:51 UTC by AdrianAndersen

- chore: use legacy ssl to support node 18
- feat(next): enable seamless linking to bl-next /info

2023-07-02 10:57 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bytte ut bl-web/info med bl-next/info](https://trello.com/c/lzUhTmAO/724-bytte-ut-bl-web-info-med-bl-next-info)

2023-07-23 19:58 UTC, LarsSelbekk requested changes
Looks mostly good. I'm just going to comment in this one since these PRs concern the same thing. The linking looks mostly fine, but I'm not sure the bl-next info page is at parity with the old one.

- For skolekunder: "Under finner du en liste over brukte skolebøker" - no list beneath
- For VGS-elever: different schools mentioned

In addition, trying to log out from bl-next doesn't log out from bl-web and sends you back there, so when you return to bl-next you're logged in again.

2023-08-23 11:41 UTC, AdrianAndersen commented
I have addressed your concerns now @LarsSelbekk. Please check out this and the corresponding PR for bl-web 😄

2023-08-24 08:58 UTC, LarsSelbekk approved these changes

2023-08-24 09:05 UTC, merged